import { Button, VerticalBox , ListView} from "std-widgets.slint";

export struct mod_str {
    text: string,
    hidden: bool,
}

export component AppWindow inherits Window {
    in property <[mod_str]> list_mod;
    out property<bool> hide: false;

    callback up_mod();
    VerticalBox {
        Button {
            text: "Toggle";
            clicked => {
                hide = !hide;
                up_mod();
            }
        }
        ListView {
            width: 100%;
            height: 200px;
            for data in list_mod : Rectangle {
                    height: 30px;
                    Rectangle {
                        height: 25px;
                        width: 90%;
                        background: orange;
                        opacity: 100;
                        Text {
                            text: data.text;
                        }

                        states [
                            //hd when !self.visible : {
                            hd when (hide && data.hidden) : {
                                opacity: 0;
                                background: red;
    
                                out {
                                    animate * {
                                        duration: 2000ms;
                                        easing: ease-in-out;
                                    }
                                }
                                in {
                                    animate * {
                                        duration: 2000ms;
                                        easing: ease-in-out;
                                    }
                                }
                                
                            }
    
                            //nhd when self.visible: {
                            nhd when !(hide && data.hidden) : {
                                opacity: 100;
                                background: orange;
    
                                in {
                                    animate * {
                                        duration: 2000ms;
                                        easing: ease-in-out;
                                    }
                                }
                                out {
                                    animate * {
                                        duration: 2000ms;
                                        easing: ease-in-out;
                                    }
                                }
                            }
                        ]
                    }
                    /*states [
                        //hd when !self.visible : {
                        hd when (hide && data.hidden) : {
                            opacity: 0;
                            background: red;

                            out {
                                animate * {
                                    duration: 2000ms;
                                    easing: ease-in-out;
                                }
                            }
                            in {
                                animate * {
                                    duration: 2000ms;
                                    easing: ease-in-out;
                                }
                            }
                            
                        }

                        //nhd when self.visible: {
                        nhd when !(hide && data.hidden) : {
                            opacity: 100;
                            background: orange;

                            in {
                                animate * {
                                    duration: 2000ms;
                                    easing: ease-in-out;
                                }
                            }
                            out {
                                animate * {
                                    duration: 2000ms;
                                    easing: ease-in-out;
                                }
                            }
                        }
                    ]*/
            }
        }
    }
}
