import { Button, VerticalBox , ListView } from "std-widgets.slint";

export struct mod_str {
    text: string,
    hidden: bool,
}

export component AppWindow inherits Window {
    in property <[mod_str]> list_mod;
    out property<bool> hide: false;
    in property<length> anim_x: 0;
    out property<length> anim_wid: lv.width;

    callback up_mod();
    VerticalBox {
        Button {
            text: "Toggle";
            clicked => {
                hide = !hide;
                up_mod();
            }
        }
        lv := ListView {
            width: 100%;
            height: 200px;
            for data in list_mod : Rectangle {
                height: 30px;
                rect := Rectangle {
                    property<length> anim_x: root.anim_x;

                    x: 0;
                    height: 25px;
                    width: 90%;
                    background: #9400D3;
                    opacity: 100;
                    Text {
                        text: data.text;
                    }

                    states [
                        hd when (hide && data.hidden) : {
                            x: -lv.width;
                        }

                        nhd when !(hide && data.hidden) : {
                            x: data.hidden ? anim_x : 0;

                            in {
                                animate x {
                                    delay: 250ms;
                                    duration: 250ms;
                                    easing: ease-in-out;
                                }
                            }
                            out {
                                animate x {
                                    duration: 250ms;
                                    easing: ease-in-out;
                                }
                            }
                        }
                    ]
                }
            }
        }
    }
}